name: Build the service and deploy to k8s
on: push
  
jobs:
  version-identifier:
    runs-on: ubuntu-latest
    steps:
      - name: set version identifier
        run: echo "VERSION_IDENTIFIER=0.1.${GITHUB_RUN_NUMBER}_${GITHUB_RUN_ATTEMPT}_${GITHUB_SHA:0:7}" | tee $GITHUB_ENV
    outputs:
      version_identifier: ${{ env.VERSION_IDENTIFIER }}

  download-image :
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ format('arn:aws:iam::{0}:role/GithubActionsECRAccess', secrets.ACCOUNT_ID) }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: docker/login-action@v3
        with:
          registry: ${{ format('{0}.dkr.ecr.{1}.amazonaws.com', secrets.ACCOUNT_ID, secrets.AWS_REGION) }}    
        
      - name: update the manifest with new image
        env:
          GH_TOKEN: ${{ secrets.LEANSPACE_BOT_TOKEN }}
          IMAGE_NAME: ${{ format('{0}.dkr.ecr.{1}.amazonaws.com/asset-repository-kubernetes:0.1.870_1_57b4ae', secrets.ACCOUNT_ID, secrets.AWS_REGION )}}
        run: |
          sed -i 's|image: ${{ steps.login-ecr.outputs.registry }}/asset-repository-kubernetes:.*|image: ${{ steps.login-ecr.outputs.registry }}/asset-repository-kubernetes:0.1.870_1_57b4ae|g' asset-manifests/deployment.yaml
          git config --global user.name 'leanspace-bot'
          git config --global user.email 'leanspace-bot@users.noreply.github.com'
          git commit -am " Updated manifest with the the latest release " --allow-empty
          git pull --rebase
          git push