name: Build the service and deploy to k8s
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  version-identifier:
    runs-on: ubuntu-latest
    steps:
      - name: set version identifier
        run: echo "VERSION_IDENTIFIER=0.1.${GITHUB_RUN_NUMBER}_${GITHUB_RUN_ATTEMPT}_${GITHUB_SHA:0:7}" | tee $GITHUB_ENV
    outputs:
      version_identifier: ${{ env.VERSION_IDENTIFIER }}

  download-image :
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            persist-credentials: false
            repository: heenasejwal216/test-cicd.git
            ref: main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ format('arn:aws:iam::{0}:role/GithubActionsECRAccess', secrets.ACCOUNT_ID) }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: docker/login-action@v3
        with:
          registry: ${{ format('{0}.dkr.ecr.{1}.amazonaws.com', secrets.ACCOUNT_ID, secrets.AWS_REGION) }}  

      - name: Set up Git
        run: |
            git config --global user.name 'heenasejwal216'
            git config --global user.email 'heena@leanspace.io'
        
      - name: update the manifest with new image
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
        run: |
          sed -i 's|image: ${{ steps.login-ecr.outputs.registry }}/asset-repository-kubernetes:.*|image: ${{ steps.login-ecr.outputs.registry }}/asset-repository-kubernetes:0.1.870_1_57b4ae|g' manifests/deployment.yaml
          git add manifests/deployment.yaml
          git commit -am " Updated manifest with the the latest release " --allow-empty
          git pull --rebase
          git push origin main
